### ISSUE TITLE
Webform - asterisks on required fields

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_frontend#66]
Most of these are okay.  I would suggest that you add:

(*) for Report Files/File URL 
(*) for Report Files/OR Upload Files
(*) for Programmes/Programme Name 

These are required conditionally.

Remove:
* from Core Data/Local Identifier
* from Core Data/Valid To

**Comment by JoshBone** [comment]
I'm not sure about using three different types of markers. @ctueck - What do you think? Shouldn't we stick just to mark the required fields? All the broader explanation can go in the infobox later.

**Comment by ctueck** [comment]
Hm, not sure how to best visualise the requirement for file upload or URL. How about having those fields so that the other one becomes inactive when you use/fill one? (E.g. similar to report links, where the display name only becomes active once you enter a link - just here the logic would be inverse)

But I don't think this is "mission-critical" for rolling out the form - only removing the asterisks (and corresponding logic) from local identifier & valid to is critical

**Comment by Gyukat** [comment]
I only meant two ways of doing it:
(*) = required conditionally
 * = required  

I just shows up weird in the interface

**Comment by ctueck** [comment]
Sounds good to me!

I added the urgent label to it mainly for the core data tab: Local Identifier & Valid To should really not be required.
